update documentation
biowdl/BamMetrics pull request #18
Opened 2019-08-13 09:48 UTC by rhpvorderman

### Checklist
- [x] Pull request details were added to CHANGELOG.md

2019-08-13 09:53 UTC, DavyCats requested changes

2019-08-13 09:53 UTC, DavyCats commented on docs/index.md
> +An output directory can be set using an `options.json` file. See [the
I think there are some ``` missing here.

2019-08-13 09:54 UTC, rhpvorderman commented on docs/index.md
> +An output directory can be set using an `options.json` file. See [the
Thanks!

2019-08-13 13:06 UTC, DavyCats requested changes

2019-08-13 13:06 UTC, DavyCats commented on docs/index.md
> +```
```suggestion
```

2019-08-14 06:31 UTC, DavyCats approved these changes

2019-08-14 11:58 UTC, merged